export const CREATE_RECORD = 'CREATE_RECORD'
export const UPDATE_RECORD = 'UPDATE_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'

export const UPDATE_MOVIE_IN_FORM = 'UPDATE_MOVIE_IN_FORM'
export const UPDATE_ACTOR_IN_FORM = 'UPDATE_ACTOR_IN_FORM'

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'
export const UPDATE_SEARCH_TYPE = 'UPDATE_SEARCH_TYPE'

export const RATE_MOVIE = 'RATE_MOVIE'

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'
